CONFIG_PRINTK=y
CONFIG_MULTITHREADING=y
CONFIG_NUM_PREEMPT_PRIORITIES=15
CONFIG_NUM_COOP_PRIORITIES=15
CONFIG_TIMESLICING=y
CONFIG_TIMESLICE_SIZE=10
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_LOG=y
